services:
  core-postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_DB=discount_code
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=pass1234
    ports:
      - '5432:5432'
  pg-admin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@localhost.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - '5050:5050'